"""empty message

Revision ID: 1f86b8312b1b
Revises: 
Create Date: 2023-03-01 20:42:05.793967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f86b8312b1b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('all_coins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('all_coins', schema=None) as batch_op:
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
